- name: Ensure Actual folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/actual"
    state: directory

- name: Copy Actual docker compose file
  ansible.builtin.template:
    src: actual.j2
    dest: "/home/{{ user }}/docker-containers/actual/docker-compose.yml"

- name: Start Actual
  ansible.builtin.shell: "cd /home/{{ user }}/docker-containers/actual && docker compose down && docker compose up -d"