- name: Ensure Docker Socket Proxy folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/docker-socket-proxy"
    state: directory

- name: Copy Docker Socket Proxy docker compose file
  ansible.builtin.template:
    src: docker-socket-proxy.j2
    dest: "/home/{{ user }}/docker-containers/docker-socket-proxy/docker-compose.yml"

- name: Start Docker Socket Proxy
  ansible.builtin.shell: "cd /home/{{ user }}/docker-containers/docker-socket-proxy && docker compose down && docker compose up -d"