- name: Ensure Prowlarr folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/prowlarr"
    state: directory

- name: Copy Prowlarr docker compose file
  ansible.builtin.template:
    src: prowlarr.j2
    dest: "/home/{{ user }}/docker-containers/prowlarr/docker-compose.yml"

- name: Ensure media network exists
  community.docker.docker_network:
    name: media
    state: present

- name: Start Prowlarr
  ansible.builtin.shell: "cd /home/{{ user }}/docker-containers/prowlarr && docker compose down && docker compose up -d"