name: Mirroring

on: [push, delete]

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  to_codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@codeberg.org:davnpsh/${{ env.REPO_NAME }}.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
